# Generated by Django 3.2.6 on 2021-10-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('content', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='No biography provided.', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
