# Generated by Django 3.2.6 on 2021-10-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(default=''),
        ),
    ]
