# Generated by Django 3.2.6 on 2021-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(default=' '),
        ),
    ]
